version: "3.9"

services:
  legends-db:
    image: postgres:15.1-alpine
    container_name: legends-database
    restart: always
    volumes:
      #      - ./data:/var/lib/postgresql/data
      - ./data/01-schema.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./data/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    environment:
      - POSTGRES_DB=legends
      - POSTGRES_USER=LegendsNick
      - POSTGRES_PASSWORD=Legends
    ports:
      - "5432:5432"